include:
  - template: Composer.gitlab-ci.yml

stages:
  - test
  - build

publish:
  if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

run_tests:
  image: composer:1
  stage: test
  script:
    - composer update --ignore-platform-reqs
    - composer test
