include:
  - template: Composer.gitlab-ci.yml

stages:
  - test
  - build

publish:
  rules:
    - if: '$CI_COMMIT_BRANCH == "stable"'

run_tests:
  image: composer:1
  stage: test
  script:
    - composer update --ignore-platform-reqs
    - composer test
  allow_failure: true
